server.port=8000

spring.h2.console.path=/h2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.initialization-mode=always

# ADD THESE TWO LINES
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

jwt.secret=mysecretkey
jwt.token.validity=3600000
