spring.application.name=notification

spring.datasource.url=jdbc:mysql://localhost:3306/notification_db
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=update


yqmo wcle sbya nltn


# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=appawar1857@gmail.com
spring.mail.password=yqmo wcle sbya nltn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true